### ISSUE TITLE
[Discussion] Content of the repository

### ISSUE THREAD

**Issue by tmnd1991** [agile-lab-dev/lake-sharing#2]
The repository will contain the following components:
- a protocol that is additive to original delta-sharing, which means that it is 100% compatible with delta-sharing and adds any missing feature needed to:
  - administer the shares (covered only by Databricks API)
  - read tables that are not supported by delta-sharing (iceberg, hive-style, hudi etc)
- a server implementation: the server implementation will implement both delta-sharing and lake-sharing protocols
- lake-sharing clients: there is no need for us to fork delta-sharing clients, they can live on their own and be maintained in their respective repos, we will host only lake-sharing clients which maybe forks of delta-sharing ones or completely new ones

The protocol will be published as an OpenApi 3.0 spec.

I would implement the server and core library copying [nessie](https://github.com/projectnessie/nessie/) tech stack, Java + Quarkus on the server side, built using Gradle. In this way we can:
- leverage the large java/quarkus community to build the server implementation
- optionally build the server as a native image 
- leverage gradle to easily build also clients/connectors developed in different languages (python/js/rust)

For the server implementation I would go with a code-gen approach starting from the OpenAPI descriptor so that we're sure that we are 100% compatible with the spec.

**Comment by tmnd1991** [comment]
Mind having a review and discussing it here @erond ?

**Comment by tmnd1991** [comment]
After agreeing on the direction to take, I would open a PR where we write a new README.md stating the goals of the project and its execution, I would start it something like:

---

# Lake Sharing: An Open Protocol for Secure Data Sharing

Fork of [Delta-Sharing](https://github.com/delta-io/delta-sharing) with the following goals:

- allow to share data in different table formats (iceberg, hudi, hive-style) leveraging the additional delta-sharing protocol and adding new APIs where needed
- provide a production-grade server implementation of both the original delta-sharing protocol and the new lake-sharing protocol

This repository contains:
- the original delta-sharing protocol
- the lake-sharing protocol
- server implementation of both protocols
- lake-sharing clients

**Comment by erond** [comment]
As correctly stated, the project aims to be additive to the original delta-sharing ones. In order to avoid as much as possible alignement maintenance effort when a new version of delta-sharing comes out, can we further discuss the way we could be "additive" with less impact as possible? 

A further discussion could be worthwhile also on the clients side: how can we target the current delta-sharing users without impacting them at all in transitioning to the lake-sharing protocol?

**Comment by tmnd1991** [comment]
In this repo I would keep:
- openapi spec of delta-sharing protocol + protocol.md description, it's 2 text files, easy to diff and update "manually", we could also write a bot to be notified when changes happen in the main repo
- openapi spec of lake-sharing protocol (i.e. the additions), those do not need to be synced

Our server implementation will be completely different from original reference one, so I would not bother to align it anyhow.

as soon as we have clients/connectors, if we are able to fork the original delta-lake implementation of those clients (which resides in the delta-io/delta-sharing repo) I would place them exactly in the same place of the repo so that it's easy to diff them.

From a user-perspective anyway, users that do not need lake-sharing features (i.e. the original protocol is enough for their needs) they can still use our server implementation with original delta-sharing clients. For users that need lake-sharing additional capabilities, they will need to use our clients/connectors that will be different from the "original" ones.

**Comment by tmnd1991** [comment]
I will open a PR where I will delete everything and add a `README.md` stating what we discussed/are discussing.
